### ISSUE TITLE
Subtype 01.17.21 non reconnu

### ISSUE THREAD

**Issue by yomgui00** [reseauphast/ParserIO#1]
Le code barre ci-dessous (**01006431690270911722042321B718589**) n'est pas entièrement reconnu par le parserIO. Le n° de série B718589 situé après le marqueur (21) n'est pas trouvé.
![code_barre_01 17 21](https://user-images.githubusercontent.com/14163/28663819-bdca1b60-72be-11e7-8d11-2df70837c06b.png)

**Comment by davideusai** [comment]
Bonjour Guillaume, je travaille actuellement sur la prochaine version de ParserIO.
Hélas je n'arrive pas à reproduire ce bug. Je suis en version 2.0.0.0 et il retourne bien le serial B718589. Ci-dessous une capture d'écran:
![image](https://user-images.githubusercontent.com/11784134/28867765-7ff7ffec-7777-11e7-8d3e-ab01eb364e96.png)

Si je ne comprends pas je risque d'écraser le branch avec le prochain merge, alors j'attends avant de le faire. Merci d'avance pour ton aide

**Comment by davideusai** [comment]
Pour info, la méthode SubType() est obsolète. Elle reste dans le projet mais elle n'est utilisée que dans la version 1.0 du Core. La version 2.0, qui implemente un pattern recursif, elle ne l'utilise plus. Tu disposes bien de la dernière version?

**Comment by yomgui00** [comment]
C'est de ma faute. J'ai pris le code dans ParserIO.Core/Functions.cs alors qu'il fallait prendre  ParserIO.Core/Functions2_0.cs
