### ISSUE TITLE
NaS 012

### ISSUE THREAD

**Issue by humantool** [reseauphast/ParserIO#5]
Hi,

In version 2.2.1.1, in data directory, the file "Barcodestore_master_20180829154420.xml" always contains barcode "SEM171252^P30778E4009A" corrsponding to NaS 012.

**Comment by humantool** [comment]
Nevermind I misunderstood your update with the case of 012 : no issue

**Comment by davideusai** [comment]
Hi,
Yes and de regular expression is still active in Parse methode. So which is exactly de problem? Why the presence of the 012 case trouble you?
